export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  CHECK_EMAIL: "/check-email",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  RESEND_VERIFICATION: "/resend-verification",
  DASHBOARD: "/dashboard",
  NOTES: "/notes",
  ARCHIVED: "/archived",
  TAGS: "/tags",
  NOTE: "/note",
} as const;
